# Generated by Django 4.0.3 on 2022-07-10 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_blogpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 10, 18, 35, 5, 826016)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
